version: "3.7"

services:

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    networks:
      - api-net
    ports:
      - "5672:5672"
    restart: on-failure

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - api-net
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
#    command: bash -c "\
#      python manage.py collectstatic --no-input && \
#      python manage.py migrate && \
#      python manage.py runserver 0.0.0.0:8000"
#      gunicorn pdf_api.wsgi -b 0.0.0.0:8000"
    container_name: app
    depends_on:
      - postgres
      - rabbitmq
    expose:
      - "8000"
    hostname: app
    image: app-image
    networks:
      - api-net
    restart: on-failure

  celery_worker:
    command: bash -c "wait-for rabbitmq:5672 -- \
      wait-for app:8000 -- celery -A pdf_api worker -l info"
    container_name: celery_worker
    depends_on:
      - app
      - postgres
      - rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    hostname: celery_worker
    image: app-image
    networks:
      - api-net
    restart: on-failure

  celery_beat:
    command: bash -c "wait-for rabbitmq:5672 -- \
      wait-for app:8000 -- celery -A pdf_api beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    container_name: celery_beat
    depends_on:
      - app
      - postgres
      - rabbitmq
    hostname: celery_beat
    image: app-image
    networks:
      - api-net
    restart: on-failure

networks:
  api-net:

volumes:
  postgresql-data: {}

