# Generated by Django 3.0.3 on 2020-05-17 09:35

from django.db import migrations, models
import django.db.models.deletion
import mask.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaskRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=10)),
                ('image', models.ImageField(default=None, upload_to=mask.models.original_image_path)),
                ('mask_method', models.CharField(max_length=10)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SB', 'StandBy'), ('PR', 'Processing'), ('FN', 'Finish'), ('ER', 'Error'), ('EX', 'Expired')], default='SB', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('result', models.ImageField(blank=True, upload_to=mask.models.result_image_path)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('mask_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.MaskRequest')),
            ],
        ),
    ]
