# Generated by Django 3.0.3 on 2020-05-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maskresult',
            old_name='result',
            new_name='result_image',
        ),
        migrations.RemoveField(
            model_name='maskresult',
            name='name',
        ),
        migrations.AlterField(
            model_name='maskrequest',
            name='author',
            field=models.EmailField(max_length=40),
        ),
    ]
