# Generated by Django 3.0.3 on 2020-05-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0002_auto_20200517_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='maskresult',
            name='mask_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mask.MaskRequest'),
        ),
    ]
