# Generated by Django 3.0.3 on 2020-05-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0003_auto_20200518_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskresult',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maskresult',
            name='mask_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mask.MaskRequest'),
        ),
    ]
