# Generated by Django 3.0.3 on 2020-05-18 05:54

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0004_auto_20200518_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskresult',
            name='mask_request',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mask.MaskRequest'),
        ),
    ]
