# Generated by Django 3.0.3 on 2020-05-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0005_auto_20200518_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskresult',
            name='mask_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mask.MaskRequest'),
        ),
    ]
