# Generated by Django 3.0.3 on 2020-05-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0006_auto_20200518_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maskresult',
            old_name='mask_request',
            new_name='request',
        ),
    ]
