# Generated by Django 3.0.3 on 2020-05-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0007_auto_20200518_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maskrequest',
            old_name='mask_method',
            new_name='method',
        ),
    ]
