# Generated by Django 3.0.3 on 2020-05-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0010_auto_20200522_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskrequest',
            name='seg_method',
            field=models.CharField(choices=[('DLR', 'DeepLabV3_Resnet101'), ('FCNR', 'FCN_ResNet101')], default='DLR', max_length=5),
        ),
    ]
